In [1]:
import numpy as np

In [1]:
from time import process_time

py_list = [i for i in range(10000)]

start = process_time()

py_list = [i+5 for i in range(10000)]

end = process_time()

print(end-start)

0.0022007359999998144


In [4]:
import numpy as np
np_array = np.array([i for i in range(10000)])

start = process_time()

np_array += 5

end = process_time()

print(end-start)


0.00016690300000021807


In [3]:
import numpy as np
np_array = np.array([i for i in range(10000)])

start = process_time()

np_array += 5

end = process_time()

print(end-start)

0.0016912869999998748


Numpy Array


In [1]:
import numpy as np
y = np.zeros((4,5))
print(y)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [2]:
z = np.ones((5,5))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [3]:
z = np.full((5,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [4]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
f = np.random.random((3,4))
print(f)


[[0.31399642 0.18585892 0.36424495 0.42750306]
 [0.67024939 0.39980893 0.75792704 0.50559112]
 [0.11536493 0.55748451 0.15511068 0.32188594]]


In [8]:
g = np.random.randint(1,10,(4,4))
print(g)

[[2 5 3 4]
 [1 3 2 6]
 [2 5 1 1]
 [1 7 3 8]]


In [20]:
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


Here We also mention the step ( starting_val , ending_val , step )

In [22]:
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


List to Numpy array

In [24]:
list_1 = [1,2,3,4,5]
np_arr = np.asarray(list_1)
print(np_arr)
type(np_arr)

[1 2 3 4 5]


numpy.ndarray

In [25]:
print(np_arr.ndim)

1


In [26]:
print(np_arr.shape)

(5,)


In [27]:
print(np.shape(np_arr))

(5,)


Size Represent** total number of elements** in nparray

In [28]:
print(np_arr.size)
print(np_arr.dtype)

5
int64


In [31]:
a = np.random.randint(1,10,(4,4))
b = np.random.randint(1,10,(4,4))

print(a)
print(b)

print("Add")
print(a+b)
print("Sub")
print(a-b)
print("Mul")
print(a*b)
print("Div")
print(a/b)

print("Add")
print(np.add(a,b))
print("Sub")
print(np.subtract(a,b))
print("Mul")
print(np.multiply(a,b))
print("Div")
print(np.divide(a,b))


[[3 8 6 1]
 [1 8 5 2]
 [1 9 4 2]
 [3 1 9 8]]
[[5 6 8 2]
 [4 9 2 2]
 [7 6 8 4]
 [4 7 4 4]]
Add
[[ 8 14 14  3]
 [ 5 17  7  4]
 [ 8 15 12  6]
 [ 7  8 13 12]]
Sub
[[-2  2 -2 -1]
 [-3 -1  3  0]
 [-6  3 -4 -2]
 [-1 -6  5  4]]
Mul
[[15 48 48  2]
 [ 4 72 10  4]
 [ 7 54 32  8]
 [12  7 36 32]]
Div
[[0.6        1.33333333 0.75       0.5       ]
 [0.25       0.88888889 2.5        1.        ]
 [0.14285714 1.5        0.5        0.5       ]
 [0.75       0.14285714 2.25       2.        ]]
Add
[[ 8 14 14  3]
 [ 5 17  7  4]
 [ 8 15 12  6]
 [ 7  8 13 12]]
Sub
[[-2  2 -2 -1]
 [-3 -1  3  0]
 [-6  3 -4 -2]
 [-1 -6  5  4]]
Mul
[[15 48 48  2]
 [ 4 72 10  4]
 [ 7 54 32  8]
 [12  7 36 32]]
Div
[[0.6        1.33333333 0.75       0.5       ]
 [0.25       0.88888889 2.5        1.        ]
 [0.14285714 1.5        0.5        0.5       ]
 [0.75       0.14285714 2.25       2.        ]]


Manipulation On nparray

In [32]:
trans = np.transpose(a)
print(trans)

[[3 1 1 3]
 [8 8 9 1]
 [6 5 4 9]
 [1 2 2 8]]


In [33]:
trans2 = a.T
print(trans2)

[[3 1 1 3]
 [8 8 9 1]
 [6 5 4 9]
 [1 2 2 8]]
